# Redirect with a 301
[[redirects]]
from = "/home"
to = "/"
status = 301

# Redirect with a 302
[[redirects]]
from = "/my-redirect"
to = "/"
status = 302

# Show a custom 404 for this path
[[redirects]]
from = "/ecommerce"
to = "/store-closed"
status = 404

# Rewrite a path
[[redirects]]
from = "/pass-through"
to = "/index.html"
status = 200

[[redirects]]
from = "/en/*"
to = "/en/404.html"
status = 404