# Redirect with a 301
[[redirects]]
from = "/home"
to = "/"
status = 301

[[redirects]]
from = "/index.html"
to = "/"
status = 301

[[redirects]]
from = "/contact.html"
to = "/contact"
status = 301


[[redirects]]
from = "/*"
to = "/404.html"
status = 404

[[redirects]]
from = "/404.html"
to = "/404"
status = 404